// Five dungeons authored as ASCII rooms (25x15 each) + parser.
//
// Legend: '#' wall  '.' floor  ',' decor  '~' deep water  '%' lava  '^' spikes  '-' gust (pushes south)
//   'D' open door   'K' locked door (small key)   'B' boss door (Big Fang)   'G' shut door (room trigger)
//   'X' cracked wall (bomb)  'E' eye switch  'P' floor plate  'O' push block  'T' torch  '@' pot
//   'S' exit stairs  's' player spawn  '1'-'9' chest  'a'-'e' enemies (per-dungeon legend)
//   'M' miniboss  'Z' boss  '!' kill-all trigger marker
// Door positions are fixed: N wall = row 0 col 12, S wall = row 14 col 12, W wall = row 7 col 0,
// E wall = row 7 col 24 — so doors in adjacent rooms always form a two-tile pair.

import { ROOM_W, ROOM_H, TILE } from './config.js';
import { T } from './tiles.js';

const WALL = '#########################';
const EMPT = '#.......................#';
const DOOR_NS = (ch) => '############' + ch + '############';
const SIDE = (l, r) => l + '.......................' + r;

// ---------------- FIRE: The Molten Maw ----------------
const FIRE = {
  id: 'fire', theme: 'fire', name: 'The Molten Maw', music: 'dungeon',
  legend: { a: 'snapjaw', b: 'emberfox', c: 'mgoanna', d: 'kooka' },
  miniboss: 'mini_fox', minibossName: 'Ember Matron', boss: 'boss_scorchjaw', bossName: 'SCORCHJAW, THE CROC-DRAGON',
  chests: { 1: { key: 1 }, 2: { coins: 80, diamonds: 2 }, 3: { bigfang: 1 }, 4: { arrowType: 'fire' } },
  layout: ['GHE', 'CBD', '.A.'],
  rooms: {
    A: [ // entry
      DOOR_NS('D'),
      '#T,,,,,,,,,,,,,,,,,,,,,T#',
      '#..%%.............%%....#',
      '#..%%..............%%...#',
      EMPT,
      EMPT,
      EMPT,
      EMPT,
      EMPT,
      '#......@.......@........#',
      EMPT,
      '#...........s...........#',
      '#...........S...........#',
      EMPT,
      WALL,
    ],
    B: [ // hub: kill-all opens side doors; locked door north
      DOOR_NS('K'),
      '#,.....................,#',
      '#...a........%%.....b...#',
      '#...........%%%.........#',
      '#....c........%.........#',
      EMPT,
      '#.....!.................#',
      SIDE('G', 'G'),
      EMPT,
      '#..%%..........a........#',
      '#..%%%..................#',
      '#...%.......@...........#',
      EMPT,
      EMPT,
      DOOR_NS('D'),
    ],
    C: [ // key chest + eye switch opens north door
      '######E#####G############',
      '#,.....................,#',
      '#..b.................b..#',
      EMPT,
      '#....%%%.......%%%......#',
      '#....%.%.......%.%......#',
      '#....%%%.......%%%......#',
      SIDE('#', 'G'),
      EMPT,
      '#...........1...........#',
      EMPT,
      '#..@..................@.#',
      '#,.....................,#',
      EMPT,
      WALL,
    ],
    D: [ // lava maze guarding the Big Fang
      WALL,
      '#,,%%%%%...........%%%%,#',
      '#..%%..................,#',
      '#......%%%%%%%%%%%......#',
      '#..d...%...........c....#',
      '#......%....%%%%%%%%%%..#',
      '#......%....%........%..#',
      SIDE('G', '#'),
      '#......%....%..3.....%..#',
      '#......%....%........%..#',
      '#..c...%....%%%%%%.%%%..#',
      '#......%................#',
      '#..%%..%.....a..........#',
      '#,.%%..................,#',
      WALL,
    ],
    G: [ // treasure room
      WALL,
      '#T,,,,,,,,,,,,,,,,,,,,,T#',
      '#.......................#',
      '#....@....2........@....#',
      EMPT,
      '#...%%..........%%......#',
      '#...%%..........%%......#',
      EMPT,
      '#..........@............#',
      EMPT,
      EMPT,
      EMPT,
      EMPT,
      EMPT,
      DOOR_NS('G'),
    ],
    H: [ // miniboss + fire arrows, boss door east
      WALL,
      '#T,,,,,,,,,,,,,,,,,,,,,T#',
      '#...........4...........#',
      EMPT,
      '#....%%............%%...#',
      EMPT,
      EMPT,
      SIDE('#', 'B'),
      '#...........M...........#',
      EMPT,
      '#....%%............%%...#',
      EMPT,
      EMPT,
      EMPT,
      DOOR_NS('K'),
    ],
    E: [ // BOSS: Scorchjaw
      WALL,
      '#,%%%,,,,,,,,,,,,,,,%%%,#',
      '#..%%...............%%..#',
      EMPT,
      EMPT,
      EMPT,
      '#................Z......#',
      SIDE('B', '#'),
      EMPT,
      EMPT,
      EMPT,
      '#..%%...............%%..#',
      '#,%%%,,,,,,,,,,,,,,,%%%,#',
      EMPT,
      WALL,
    ],
  },
};

// ---------------- WATER: The Sunken Grotto ----------------
const WATER = {
  id: 'water', theme: 'water', name: 'The Sunken Grotto', music: 'dungeon',
  legend: { a: 'volteel', b: 'cod', c: 'snapshell' },
  miniboss: 'mini_eel', minibossName: 'Eel Matron', boss: 'boss_murkmaw', bossName: 'MURKMAW, THE GULPER LEVIATHAN',
  chests: { 1: { key: 1 }, 2: { bigfang: 1 }, 3: { arrowType: 'ice' }, 4: { diamonds: 3 }, 5: { coins: 60 } },
  layout: ['EFH', 'CBG', '.AD'],
  rooms: {
    A: [ // entry
      DOOR_NS('D'),
      '#,.....................,#',
      '#..~~~.............~~~..#',
      '#..~~~.............~~~..#',
      EMPT,
      EMPT,
      EMPT,
      SIDE('#', 'D'),
      EMPT,
      '#......@.......@........#',
      EMPT,
      '#...........s...........#',
      '#...........S...........#',
      EMPT,
      WALL,
    ],
    D: [ // bonus room east of entry
      WALL,
      '#,.....................,#',
      '#..~~~~~~..........c....#',
      '#..~~~~~~~..............#',
      '#..~~a~~~~~.............#',
      '#...~~~~~..........@....#',
      '#....................5..#',
      SIDE('D', '#'),
      '#..................@....#',
      '#...c...................#',
      '#..........~~~~.........#',
      '#.........~~b~~~........#',
      '#..........~~~~.........#',
      '#,.....................,#',
      WALL,
    ],
    B: [ // hub: eye switch across the water opens both side doors
      '########E###K############',
      '#,.....................,#',
      '#..~~~~~~~~~~~~~~~~~~~..#',
      '#..~~~~~~~~a~~~~~~~~~~..#',
      '#..~~~~b~~~~~~~~a~~~~~..#',
      '#..~~~~~~~~~~~~~~~~~~~..#',
      EMPT,
      SIDE('G', 'G'),
      EMPT,
      '#...c...........c.......#',
      EMPT,
      '#..........@............#',
      EMPT,
      EMPT,
      DOOR_NS('D'),
    ],
    C: [ // kill-all for the key
      WALL,
      '#,.....................,#',
      '#...~~~~......~~~~......#',
      '#...~a~~......~b~~......#',
      '#...~~~~......~~~~......#',
      EMPT,
      '#......!................#',
      SIDE('#', 'G'),
      EMPT,
      '#...........1...........#',
      EMPT,
      '#...c...............c...#',
      '#,.....................,#',
      EMPT,
      WALL,
    ],
    G: [ // swim maze guarding the Big Fang
      WALL,
      '#,~~~~~~~~~~~~~~~~~~~~~,#',
      '#.~~~~~~~~~~~~~~~~~~~~~.#',
      '#.~~....~~~~~~~~....~~~.#',
      '#.~~.2..~~~a~~~~..a.~~~.#',
      '#.~~....~~~~~~~~....~~~.#',
      '#.~~~~~~~~~~~~~~~~~~~~~.#',
      SIDE('G', '#'),
      '#.~~~~~a~~~~~~~~b~~~~~~.#',
      '#.~~~~~~~~~~~~~~~~~~~~~.#',
      '#.~~~~~~~~~~~~~~~~~~~~~.#',
      '#.......................#',
      '#..@..................@.#',
      '#,.....................,#',
      WALL,
    ],
    F: [ // miniboss pool + ice arrows; treasure west, boss east
      WALL,
      '#T,,,,,,,,,,,,,,,,,,,,,T#',
      '#...........3...........#',
      '#..........!............#',
      '#....~~~~~~~~~~~~~~~....#',
      '#....~~~~~~~~~~~~~~~....#',
      '#....~~~~~~M~~~~~~~~....#',
      SIDE('G', 'B'),
      '#....~~~~~~~~~~~~~~~....#',
      '#....~~~~~~~~~~~~~~~....#',
      EMPT,
      EMPT,
      EMPT,
      EMPT,
      DOOR_NS('K'),
    ],
    E: [ // treasure
      WALL,
      '#T,,,,,,,,,,,,,,,,,,,,,T#',
      EMPT,
      EMPT,
      '#..........4............#',
      EMPT,
      EMPT,
      SIDE('#', 'G'),
      EMPT,
      '#.....@..........@......#',
      EMPT,
      EMPT,
      '#,.....................,#',
      WALL,
      WALL,
    ],
    H: [ // BOSS: Murkmaw's pool
      WALL,
      '#,~~~~~~~~~~~~~~~~~~~~~,#',
      '#.~~~~~~~~~~~~~~~~~~~~~.#',
      '#.~~~~~~~~~~~~~~~~~~~~~.#',
      '#.~~~~~~~~Z~~~~~~~~~~~~.#',
      '#.~~~~~~~~~~~~~~~~~~~~~.#',
      '#..~~~~~~~~~~~~~~~~~~~..#',
      SIDE('B', '#'),
      '#....~~~~~~~~~~~~~~~....#',
      EMPT,
      EMPT,
      EMPT,
      '#,.....................,#',
      WALL,
      WALL,
    ],
  },
};

// ---------------- AIR: The Tempest Spire ----------------
const AIR = {
  id: 'air', theme: 'air', name: 'The Tempest Spire', music: 'dungeon',
  legend: { a: 'talon', b: 'owl', c: 'kooka' },
  miniboss: 'mini_owl', minibossName: 'Owl Sage', boss: 'boss_galestrike', bossName: 'GALESTRIKE, THE STORM EAGLE',
  chests: { 1: { key: 1 }, 2: { bigfang: 1 }, 3: { arrowType: 'lightning' }, 4: { diamonds: 3 } },
  layout: ['HG', 'EF', 'BC', 'A.'],
  rooms: {
    A: [ // entry
      DOOR_NS('D'),
      '#T,,,,,,,,,,,,,,,,,,,,,T#',
      EMPT,
      '#...,...............,...#',
      EMPT,
      EMPT,
      EMPT,
      EMPT,
      EMPT,
      '#......@.......@........#',
      EMPT,
      '#...........s...........#',
      '#...........S...........#',
      EMPT,
      WALL,
    ],
    B: [ // gust halls
      DOOR_NS('K'),
      '#,.....................,#',
      '#..^^..-----.------..^^.#',
      '#......-----.------.....#',
      '#..a...-----.------..a..#',
      '#......-----.------.....#',
      '#......-----.------.....#',
      SIDE('#', 'D'),
      '#......-----.------.....#',
      '#..^^..-----.------..^^.#',
      EMPT,
      '#.....c.................#',
      EMPT,
      EMPT,
      DOOR_NS('D'),
    ],
    C: [ // kill-all guards the key
      WALL,
      '#,.....................,#',
      '#...a...........a.......#',
      EMPT,
      '#.....^^.......^^.......#',
      EMPT,
      '#..........!............#',
      SIDE('D', '#'),
      EMPT,
      '#...........1...........#',
      '#.....^^.......^^.......#',
      '#...b...................#',
      '#,.....................,#',
      EMPT,
      WALL,
    ],
    E: [ // eye behind the gusts opens the way up
      '######E#####G############',
      '#,.....................,#',
      '#..----------------.....#',
      '#..----------------..b..#',
      '#..--^^--------^^--.....#',
      '#..----------------.....#',
      '#..----------------.....#',
      SIDE('#', 'D'),
      '#..a....................#',
      EMPT,
      '#.........c.............#',
      EMPT,
      EMPT,
      EMPT,
      DOOR_NS('K'),
    ],
    F: [ // gust + spike weave; Big Fang and diamonds
      WALL,
      '#,.....................,#',
      '#..-----^^-----^^----...#',
      '#..------------------...#',
      '#..--2---------------...#',
      '#..------------------...#',
      '#..------^^------^^--...#',
      SIDE('D', '#'),
      '#..------------------...#',
      '#..--------4---------...#',
      '#..------------------...#',
      '#...b.............b.....#',
      '#,.....................,#',
      EMPT,
      WALL,
    ],
    H: [ // miniboss + lightning arrows
      WALL,
      '#T,,,,,,,,,,,,,,,,,,,,,T#',
      '#...........3...........#',
      EMPT,
      '#...,...............,...#',
      EMPT,
      EMPT,
      SIDE('#', 'B'),
      '#...........M...........#',
      EMPT,
      '#...,...............,...#',
      EMPT,
      EMPT,
      EMPT,
      DOOR_NS('G'),
    ],
    G: [ // BOSS: Galestrike's aerie
      WALL,
      '#,,,,,,,,,,,,,,,,,,,,,,,#',
      '#..,.................,..#',
      EMPT,
      EMPT,
      EMPT,
      '#................Z......#',
      SIDE('B', '#'),
      EMPT,
      EMPT,
      EMPT,
      '#..,.................,..#',
      '#,,,,,,,,,,,,,,,,,,,,,,,#',
      WALL,
      WALL,
    ],
  },
};

// ---------------- EARTH: The Rootdeep Barrow ----------------
const EARTH = {
  id: 'earth', theme: 'earth', name: 'The Rootdeep Barrow', music: 'dungeon',
  legend: { a: 'dingo', b: 'wildcat', c: 'python', d: 'tazzy' },
  miniboss: 'mini_python', minibossName: 'Python Elder', boss: 'boss_kinggoanna', bossName: 'KING GOANNA, THE EARTHSHAKER',
  chests: { 1: { coins: 50 }, 2: { key: 1 }, 3: { bigfang: 1 }, 4: { arrowType: 'bomb' }, 5: { diamonds: 3 } },
  layout: ['FGH', 'DBE', 'CA.'],
  rooms: {
    A: [ // entry
      DOOR_NS('D'),
      '#T,,,,,,,,,,,,,,,,,,,,,T#',
      EMPT,
      '#...,...............,...#',
      EMPT,
      EMPT,
      EMPT,
      SIDE('D', '#'),
      EMPT,
      '#......@.......@........#',
      EMPT,
      '#...........s...........#',
      '#...........S...........#',
      EMPT,
      WALL,
    ],
    C: [ // bonus room
      WALL,
      '#,.....................,#',
      '#..@..................@.#',
      EMPT,
      '#....^^.........^^......#',
      '#..b.................b..#',
      EMPT,
      SIDE('#', 'D'),
      EMPT,
      '#...........1...........#',
      EMPT,
      '#..@..................@.#',
      '#,.....................,#',
      EMPT,
      WALL,
    ],
    B: [ // push-block plates open both side doors
      DOOR_NS('K'),
      '#,.....................,#',
      '#.....P.........P.......#',
      EMPT,
      EMPT,
      '#.......O.....O.........#',
      EMPT,
      SIDE('G', 'G'),
      EMPT,
      '#...a...........a.......#',
      EMPT,
      '#..........@............#',
      EMPT,
      EMPT,
      DOOR_NS('D'),
    ],
    D: [ // kill-all for the key
      WALL,
      '#,.....................,#',
      '#...a...........a.......#',
      EMPT,
      '#....,....^^.....,......#',
      EMPT,
      '#..........!............#',
      SIDE('#', 'G'),
      EMPT,
      '#...........2...........#',
      EMPT,
      '#...b...........b.......#',
      '#,.....................,#',
      EMPT,
      WALL,
    ],
    E: [ // python nest guards the Big Fang
      WALL,
      '#,.....................,#',
      '#..c......,,,......c....#',
      '#.........,,,...........#',
      EMPT,
      '#.....^^.......^^.......#',
      EMPT,
      SIDE('G', '#'),
      EMPT,
      '#...........3...........#',
      '#......c................#',
      EMPT,
      '#,.....................,#',
      EMPT,
      WALL,
    ],
    G: [ // miniboss + bomb arrows
      WALL,
      '#T,,,,,,,,,,,,,,,,,,,,,T#',
      '#...........4...........#',
      '#..........!............#',
      '#...,...............,...#',
      EMPT,
      EMPT,
      SIDE('G', 'B'),
      '#...........M...........#',
      EMPT,
      '#...,...............,...#',
      EMPT,
      EMPT,
      EMPT,
      DOOR_NS('K'),
    ],
    F: [ // treasure
      WALL,
      '#T,,,,,,,,,,,,,,,,,,,,,T#',
      EMPT,
      EMPT,
      '#..........5............#',
      EMPT,
      EMPT,
      SIDE('#', 'G'),
      EMPT,
      '#.....@..........@......#',
      EMPT,
      EMPT,
      '#,.....................,#',
      WALL,
      WALL,
    ],
    H: [ // BOSS: King Goanna
      WALL,
      '#,,,,,,,,,,,,,,,,,,,,,,,#',
      '#..^^.................^^#',
      EMPT,
      EMPT,
      EMPT,
      '#................Z......#',
      SIDE('B', '#'),
      EMPT,
      EMPT,
      EMPT,
      '#..^^.................^^#',
      '#,,,,,,,,,,,,,,,,,,,,,,,#',
      WALL,
      WALL,
    ],
  },
};

// ---------------- NEXUS: The Nexus of Fangs ----------------
const NEXUS = {
  id: 'nexus', theme: 'nexus', name: 'The Nexus of Fangs', music: 'nexus',
  legend: { a: 'gknight', b: 'owl', c: 'tazzy', d: 'snapjaw', e: 'volteel' },
  miniboss: null, boss: 'boss_apexus', bossName: 'APEXUS, THE PRIMAL CHIMERA',
  chests: { 1: { arrowType: 'light' }, 2: { bigfang: 1 }, 3: { diamonds: 4 }, 4: { coins: 150 } },
  layout: ['.HI', 'FCG', 'DBE', '.A.'],
  rooms: {
    A: [ // entry
      DOOR_NS('D'),
      '#T,,,,,,,,,,,,,,,,,,,,,T#',
      EMPT,
      '#...,...............,...#',
      EMPT,
      EMPT,
      EMPT,
      EMPT,
      EMPT,
      '#......@.......@........#',
      EMPT,
      '#...........s...........#',
      '#...........S...........#',
      EMPT,
      WALL,
    ],
    B: [ // knights guard the west spiral
      WALL,
      '#,.....................,#',
      '#...a...........a.......#',
      EMPT,
      '#....,....!......,......#',
      EMPT,
      EMPT,
      SIDE('G', 'D'),
      EMPT,
      '#.......c...............#',
      EMPT,
      '#..........@............#',
      EMPT,
      EMPT,
      DOOR_NS('D'),
    ],
    E: [ // bonus room
      WALL,
      '#,.....................,#',
      '#..@..................@.#',
      EMPT,
      '#.....c.........c.......#',
      EMPT,
      EMPT,
      SIDE('D', '#'),
      EMPT,
      '#...........4...........#',
      EMPT,
      '#..@..................@.#',
      '#,.....................,#',
      EMPT,
      WALL,
    ],
    D: [ // FIRE wing: lava spiral to the plate
      DOOR_NS('G'),
      '#,%%%..................,#',
      '#..%%....%%%%%%%%.......#',
      '#........%......%..d....#',
      '#..d.....%..%%..%.......#',
      '#........%..%%..%.......#',
      '#........%......%.......#',
      SIDE('#', 'G'),
      '#....%%%%%..%%%%%.......#',
      '#..........P............#',
      '#....%%%%%%%%%%%%.......#',
      '#..d....................#',
      '#,%%...............%%%,.#',
      EMPT,
      WALL,
    ],
    F: [ // WATER wing: eel-infested swim, eye on the wall
      '########E################',
      '#,.....................,#',
      '#..~~~~~~~~~~~~~~~~~~~..#',
      '#..~~~~~e~~~~~~~~~~~~~..#',
      '#..~~~~~~~~~~~e~~~~~~~..#',
      '#..~~~~~~~~~~~~~~~~~~~..#',
      '#..~~~e~~~~~~~~~~~~~~~..#',
      SIDE('#', 'G'),
      '#..~~~~~~~~~~~~~~~~~~~..#',
      '#..~~~~~~~~e~~~~~~~~~~..#',
      '#..~~~~~~~~~~~~~~~~~~~..#',
      EMPT,
      EMPT,
      EMPT,
      DOOR_NS('G'),
    ],
    C: [ // AIR wing: gusts and spikes to the plate
      WALL,
      '#,.....................,#',
      '#..----^^----^^-----....#',
      '#..-----------------....#',
      '#..b----------------.b..#',
      '#..-----------------....#',
      '#..---^^-----^^-----....#',
      SIDE('G', 'G'),
      '#..-----------------....#',
      '#.........P.............#',
      '#..-----------------....#',
      '#...b...................#',
      EMPT,
      WALL,
      WALL,
    ],
    G: [ // EARTH wing: block on plate opens the vault
      DOOR_NS('G'),
      '#,.....................,#',
      '#....P..................#',
      EMPT,
      '#......O................#',
      EMPT,
      '#...c...........a.......#',
      SIDE('G', '#'),
      EMPT,
      '#.....^^.......^^.......#',
      '#..........c............#',
      EMPT,
      EMPT,
      WALL,
      WALL,
    ],
    I: [ // vault: Light Arrows + Big Fang
      WALL,
      '#T,,,,,,,,,,,,,,,,,,,,,T#',
      EMPT,
      '#......1.......2........#',
      EMPT,
      EMPT,
      '#...........3...........#',
      SIDE('B', '#'),
      EMPT,
      '#...a...............a...#',
      EMPT,
      EMPT,
      EMPT,
      EMPT,
      DOOR_NS('G'),
    ],
    H: [ // BOSS: Apexus, hazards of all four elements
      WALL,
      '#,%%,,,,,,,,,,,,,,,,,~~,#',
      '#.%%.................~~.#',
      EMPT,
      EMPT,
      EMPT,
      '#...........Z...........#',
      SIDE('#', 'B'),
      EMPT,
      EMPT,
      EMPT,
      '#.^^.................--.#',
      '#,^^,,,,,,,,,,,,,,,,,--,#',
      WALL,
      WALL,
    ],
  },
};

export const DUNGEONS = { fire: FIRE, water: WATER, air: AIR, earth: EARTH, nexus: NEXUS };

const CHAR_TILE = {
  '#': T.DWALL, '.': T.DFLOOR, ',': T.DDECOR, '~': T.DWATER, '%': T.DLAVA, '^': T.SPIKES,
  '-': T.GUST, 'D': T.DOOR_OPEN, 'K': T.DOOR_LOCKED, 'B': T.DOOR_BOSS, 'G': T.DOOR_SHUT,
  'X': T.DCRACK, 'E': T.EYE, 'P': T.PLATE, 'T': T.TORCH, 'S': T.STAIRS,
};

// Build a playable Area from a dungeon definition + persistent flags.
export function buildDungeon(id, flags = {}) {
  const D = DUNGEONS[id];
  const rows = D.layout.length, cols = Math.max(...D.layout.map(r => r.length));
  const w = cols * ROOM_W, h = rows * ROOM_H;
  const tiles = new Uint8Array(w * h).fill(T.DWALL);
  const idx = (x, y) => y * w + x;
  const inB = (x, y) => x >= 0 && y >= 0 && x < w && y < h;

  const rooms = {};   // "rx,ry" -> { spawns, killall, plates, eyes, gdoors, letter }
  const propsList = [];
  let playerStart = null, exitStairs = null, bossRoom = null;

  for (let ry = 0; ry < rows; ry++) {
    for (let rx = 0; rx < cols; rx++) {
      const letter = (D.layout[ry] || '')[rx] || '.';
      if (letter === '.') continue;
      const map = D.rooms[letter];
      if (!map) continue;
      const rk = rx + ',' + ry;
      const room = { rx, ry, letter, spawns: [], killall: false, plates: [], eyes: [], gdoors: [] };
      rooms[rk] = room;
      for (let y = 0; y < ROOM_H; y++) {
        let row = map[y] || WALL;
        if (row.length < ROOM_W) row += WALL.slice(0, ROOM_W - row.length);
        for (let x = 0; x < ROOM_W; x++) {
          const ch = row[x];
          const gx = rx * ROOM_W + x, gy = ry * ROOM_H + y;
          let tile = T.DFLOOR;
          if (ch in CHAR_TILE) tile = CHAR_TILE[ch];
          else if (ch === 's') playerStart = { x: gx * TILE + 8, y: gy * TILE + 8 };
          else if (ch >= '1' && ch <= '9')
            propsList.push({ kind: 'chest', tx: gx, ty: gy, id: `d_${id}_${ch}`, contents: D.chests[ch] || { coins: 20 } });
          else if (ch === '@') propsList.push({ kind: 'pot', tx: gx, ty: gy });
          else if (ch === 'O') propsList.push({ kind: 'block', tx: gx, ty: gy });
          else if (ch === '!') room.killall = true;
          else if (ch === 'M') room.spawns.push({ x: gx * TILE + 8, y: gy * TILE + 8, type: D.miniboss, miniboss: true });
          else if (ch === 'Z') { room.spawns.push({ x: gx * TILE + 8, y: gy * TILE + 8, type: D.boss, boss: true }); bossRoom = rk; }
          else if (D.legend[ch]) room.spawns.push({ x: gx * TILE + 8, y: gy * TILE + 8, type: D.legend[ch] });

          // persistent opened doors / bombed walls
          if ((tile === T.DOOR_LOCKED || tile === T.DCRACK || tile === T.DOOR_BOSS) && flags[`door_${id}_${gx}_${gy}`])
            tile = T.DOOR_OPEN;
          if (tile === T.STAIRS) exitStairs = { tx: gx, ty: gy };
          if (tile === T.PLATE) room.plates.push({ x: gx, y: gy });
          if (tile === T.EYE) room.eyes.push({ x: gx, y: gy });
          if (tile === T.DOOR_SHUT) room.gdoors.push({ x: gx, y: gy });
          tiles[idx(gx, gy)] = tile;
        }
      }
    }
  }

  return {
    id, type: 'dungeon', theme: D.theme, name: D.name, music: D.music,
    w, h, tiles, rooms, bossRoom,
    get: (x, y) => inB(x, y) ? tiles[idx(x, y)] : T.DWALL,
    set: (x, y, t) => { if (inB(x, y)) tiles[idx(x, y)] = t; },
    regionAt: () => -1,
    spawners: [], props: propsList,
    playerStart, exitStairs,
    roomAt: (px, py) => {
      const rx = Math.floor(px / (ROOM_W * TILE)), ry = Math.floor(py / (ROOM_H * TILE));
      return rooms[rx + ',' + ry] || null;
    },
    minibossName: D.minibossName, bossName: D.bossName,
  };
}
